export const REQUEST_HOME = 'REQUEST_HOME'
export const REQUEST_AUTHOR_INFO = 'REQUEST_AUTHOR_INFO'
export const REQUEST_MOST_WATCH = 'REQUEST_MOST_WATCH'
export const RESPONSE_PLAYER_DATA_NULL = 'RESPONSE_PLAYER_DATA_NULL'
